# PARENT_ITEM -> ITEM_ID 로 업그레이드 되는 거임
SELECT INFO.ITEM_ID, INFO.ITEM_NAME, INFO.RARITY
FROM ITEM_INFO AS INFO
LEFT JOIN ITEM_TREE AS TREE
    ON INFO.ITEM_ID = TREE.PARENT_ITEM_ID
WHERE TREE.ITEM_ID IS NULL
ORDER BY INFO.ITEM_ID DESC