# 음식종류별로 즐겨찾기수가 가장 많은 식당의 ~ 정보
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO
# WHERE REST_NAME IN (SELECT REST_NAME FROM REST_INFO ORDER BY FAVORITES DESC LIMIT 1)
WHERE (FOOD_TYPE, FAVORITES) IN
(SELECT FOOD_TYPE, MAX(FAVORITES)
 FROM REST_INFO
 GROUP BY FOOD_TYPE
)
ORDER BY FOOD_TYPE DESC;