-- 코드를 입력하세요
SELECT R.FOOD_TYPE, R.REST_ID, R.REST_NAME, R.FAVORITES
FROM REST_INFO AS R
JOIN (
    # 즐겨찾기수가 가장 많은 식당
    SELECT FOOD_TYPE, MAX(FAVORITES) AS MAX_FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE
) AS F
ON R.FOOD_TYPE = F.FOOD_TYPE
WHERE R.FAVORITES = F.MAX_FAVORITES
ORDER BY R.FOOD_TYPE DESC