-- 코드를 입력하세요
SELECT U.USER_ID, 
U.NICKNAME, 
CONCAT(U.CITY,' ', U.STREET_ADDRESS1, ' ', U.STREET_ADDRESS2) AS 전체주소, 
CONCAT(SUBSTRING(U.TLNO,1,3),'-',SUBSTRING(U.TLNO,4,4),'-',SUBSTRING(U.TLNO,8,4)) AS 전화번호
FROM USED_GOODS_USER AS U
JOIN (
    SELECT WRITER_ID
    FROM USED_GOODS_BOARD
    GROUP BY WRITER_ID
    HAVING COUNT(*) >= 3 # 그룹핑된 결과에 조건을 거는 절임
) AS B ON B.WRITER_ID = U.USER_ID
# GROUP BY USER_ID <= select 에 있는 애들이 집계/그룹 컬럼이 아니라서 에러 남
ORDER BY U.USER_ID DESC