# SELECT OUTS.ANIMAL_ID, OUTS.NAME
# FROM ANIMAL_OUTS AS OUTS
# # JOIN ANIMAL_OUTS AS OUTS IN INS.ANIMAL_ID = OUTS.ANIMAL_ID
# WHERE OUTS.ANIMAL_ID NOT IN (SELECT INS.ANIMAL_ID FROM ANIMAL_INS AS INS)
# ORDER BY OUTS.ANIMAL_ID

-- 코드를 입력하세요
# SELECT INS.ANIMAL_ID, INS.NAME
# FROM ANIMAL_INS AS INS
# LEFT JOIN ANIMAL_OUTS AS OUTS
# ON OUTS.ANIMAL_ID = INS.ANIMAL_ID
# WHERE OUTS.ANIMAL_ID IS NULL
# ORDER BY INS.ANIMAL_ID

SELECT OUTS.ANIMAL_ID, OUTS.NAME
FROM ANIMAL_OUTS AS OUTS
LEFT JOIN ANIMAL_INS AS INS
ON OUTS.ANIMAL_ID = INS.ANIMAL_ID
WHERE INS.ANIMAL_ID IS NULL
ORDER BY OUTS.ANIMAL_ID;
