SELECT OUTS.ANIMAL_ID, OUTS.NAME
FROM ANIMAL_OUTS AS OUTS
# JOIN ANIMAL_OUTS AS OUTS IN INS.ANIMAL_ID = OUTS.ANIMAL_ID
WHERE OUTS.ANIMAL_ID NOT IN (SELECT INS.ANIMAL_ID FROM ANIMAL_INS AS INS)
ORDER BY OUTS.ANIMAL_ID