SELECT INS.NAME, INS.DATETIME
FROM ANIMAL_INS AS INS
# JOIN ANIMAL_OUTS AS OUTS ON INS.ANIMAL_ID = OUTS.ANIMAL_ID
WHERE INS.ANIMAL_ID NOT IN (SELECT OUTS.ANIMAL_ID FROM ANIMAL_OUTS AS OUTS)
ORDER BY INS.DATETIME
LIMIT 3