WITH TMP AS (
    SELECT 
        C.CAR_ID,
        C.DAILY_FEE,
        C.CAR_TYPE,
        H.HISTORY_ID,
        DATEDIFF(H.END_DATE, H.START_DATE) + 1 AS RENTAL_DAYS
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    JOIN CAR_RENTAL_COMPANY_CAR C
        ON H.CAR_ID = C.CAR_ID
    WHERE C.CAR_TYPE = '트럭'
),
APPLIED AS (
    SELECT 
        T.HISTORY_ID,
        T.DAILY_FEE,
        T.RENTAL_DAYS,
        P.DISCOUNT_RATE
    FROM TMP T
    LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
        ON P.CAR_TYPE = '트럭' 
        AND (
            (P.DURATION_TYPE = '7일 이상' AND T.RENTAL_DAYS BETWEEN 7 AND 29) OR
            (P.DURATION_TYPE = '30일 이상' AND T.RENTAL_DAYS BETWEEN 30 AND 89) OR
            (P.DURATION_TYPE = '90일 이상' AND T.RENTAL_DAYS >= 90)
        )
)
SELECT 
    HISTORY_ID, 
    FLOOR(DAILY_FEE * RENTAL_DAYS * (1 - IFNULL(DISCOUNT_RATE, 0) / 100)) AS FEE
FROM APPLIED
ORDER BY FEE DESC, HISTORY_ID DESC;