# 평가점수에 해당하는
WITH SCORES AS (
    SELECT EMP_NO, AVG(SCORE) AS SCORE
    FROM HR_GRADE
    WHERE YEAR = '2022'
    GROUP BY EMP_NO
)

SELECT E.EMP_NO, E.EMP_NAME,
CASE WHEN S.SCORE >= 96 THEN 'S'
    WHEN S.SCORE >= 90 THEN 'A'
    WHEN S.SCORE >= 80 THEN 'B'
    ELSE 'C' END AS GRADE, 
CASE WHEN S.SCORE >= 96 THEN E.SAL * 0.2
    WHEN S.SCORE >= 90 THEN E.SAL * 0.15
    WHEN S.SCORE >= 80 THEN E.SAL * 0.1
    ELSE 0 END AS BONUS
FROM HR_EMPLOYEES AS E
JOIN SCORES AS S
ON S.EMP_NO = E.EMP_NO
ORDER BY E.EMP_NO ASC;