WITH REVIEW_COUNTS AS (
    SELECT COUNT(*) AS REVIEW_COUNT, MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
), TOP_MEMBER AS (
    SELECT MEMBER_ID
    FROM REVIEW_COUNTS
    WHERE REVIEW_COUNT = (
        SELECT MAX(REVIEW_COUNT)
        FROM REVIEW_COUNTS
    )
)

SELECT M.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, "%Y-%m-%d") AS REVIEW_DATE
FROM MEMBER_PROFILE AS M
JOIN REST_REVIEW AS R
ON R.MEMBER_ID = M.MEMBER_ID
WHERE R.MEMBER_ID IN (
    SELECT MEMBER_ID
    FROM TOP_MEMBER
)
ORDER BY REVIEW_DATE, R.REVIEW_TEXT