WITH REVIEW_COUNTS AS (
    SELECT MEMBER_ID, COUNT(*) AS REVIEW_COUNT
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
),
TOP_MEMBERS AS (
    SELECT MEMBER_ID
    FROM REVIEW_COUNTS
    WHERE REVIEW_COUNT = (
        SELECT MAX(REVIEW_COUNT)
        FROM REVIEW_COUNTS
    )
)
SELECT M.MEMBER_NAME,
       R.REVIEW_TEXT,
       DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE AS M
JOIN REST_REVIEW AS R
ON M.MEMBER_ID = R.MEMBER_ID
WHERE R.MEMBER_ID IN (
    SELECT MEMBER_ID
    FROM TOP_MEMBERS
)
ORDER BY R.REVIEW_DATE ASC, R.REVIEW_TEXT ASC;
