# -- 코드를 작성해주세요
# SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY
# FROM ITEM_INFO AS I
# LEFT JOIN ITEM_TREE AS T ON I.ITEM_ID = T.PARENT_ITEM_ID
# WHERE T.PARENT_ITEM_ID IS NOT NULL AND I.RARITY = 'RARE'
# ORDER BY I.ITEM_ID DESC

# rare 를 찾는 서브 쿼리

SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM ITEM_INFO AS I
JOIN ITEM_TREE AS T 
ON I.ITEM_ID = T.ITEM_ID
WHERE T.PARENT_ITEM_ID IN (
    SELECT ITEM_ID
    FROM ITEM_INFO
    WHERE RARITY = 'RARE'
)
ORDER BY I.ITEM_ID DESC;