-- 코드를 작성해주세요
# 부모의 형질을 모두 보유 -> P.GENOTYPE & C.GENOTYPE > 0
SELECT C.ID, C.GENOTYPE, P.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA P
LEFT JOIN ECOLI_DATA C ON P.ID = C.PARENT_ID
# WHERE P.GENOTYPE & C.GENOTYPE > 0
WHERE (P.GENOTYPE & C.GENOTYPE) = P.GENOTYPE
ORDER BY C.ID
