# 연도별로 최대 크기를 구한 뒤, 
# 그 최대값과 각 개체 크기의 차이(YEAR_DEV)를 구해서 정렬
# SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, 
# (MAX(SIZE_OF_COLONY) - MIN(SIZE_OF_COLONY)) AS YEAR_DEV, ID
# FROM ECOLI_DATA
# GROUP BY ID, YEAR
# ORDER BY YEAR, YEAR_DEV

# 연도별 최대 크기를 CTE에서 구하고,
WITH MAX_SIZE_PER_YEAR AS (
    SELECT MAX(SIZE_OF_COLONY) AS MAX_SIZE, YEAR(DIFFERENTIATION_DATE) AS YEAR
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
)

# 원본 테이블과 연도로 조인해 (MAX_SIZE - SIZE_OF_COLONY) 계산하면 해결
SELECT M.YEAR, (M.MAX_SIZE - E.SIZE_OF_COLONY) AS YEAR_DEV, E.ID
FROM ECOLI_DATA AS E JOIN MAX_SIZE_PER_YEAR AS M 
ON YEAR(DIFFERENTIATION_DATE) = M.YEAR
# GROUP BY ID
ORDER BY M.YEAR, YEAR_DEV

# SELECT 
#     YEAR(DIFFERENTIATION_DATE) AS YEAR,
#     MAX(SIZE_OF_COLONY) - MIN(SIZE_OF_COLONY) AS YEAR_DEV,
#     ID
# FROM ECOLI_DATA
# GROUP BY YEAR(DIFFERENTIATION_DATE), ID
# ORDER BY YEAR;