
SELECT DISTINCT H.CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
JOIN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_CAR
    WHERE CAR_TYPE = '세단'
) AS C ON H.CAR_ID = C.CAR_ID
WHERE MONTH(H.START_DATE) = 10
ORDER BY H.CAR_ID DESC;

