WITH SCORES AS (
    SELECT EMP_NO, SUM(SCORE) AS SCORE
    FROM HR_GRADE
    WHERE YEAR = 2022
    GROUP BY EMP_NO
),
BEST AS (
    SELECT EMP_NO, SCORE
    FROM SCORES
    WHERE SCORE = (
        SELECT MAX(SCORE)
        FROM SCORES
    )
)

SELECT B.SCORE, E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM HR_EMPLOYEES AS E
JOIN BEST AS B
ON B.EMP_NO = E.EMP_NO
