# SELECT CONCAT('/home/grep/src/', F.BOARD_ID, '/', F.FILE_ID, F.FILE_NAME, FILE_EXT)
# AS FILE_PATH
# FROM USED_GOODS_BOARD AS B
# JOIN USED_GOODS_FILE AS F
# ON B.BOARD_ID = F.BOARD_ID
# # GROUP BY B.BOARD_ID, F.BOARD_ID
# ORDER BY F.FILE_ID DESC, B.VIEWS DESC
# LIMIT 1;

# SELECT CONCAT('/home/grep/src/', F.BOARD_ID, '/', F.FILE_ID, F.FILE_NAME, FILE_EXT)
# AS FILE_PATH
# FROM USED_GOODS_FILE AS F
# WHERE F.BOARD_ID IN (
#     SELECT B.BOARD_ID
#     FROM USED_GOODS_BOARD AS B
#     ORDER BY B.PRICE DESC
# )
# ORDER BY F.FILE_ID DESC;

SELECT 
  CONCAT('/home/grep/src/', F.BOARD_ID, '/', F.FILE_ID, F.FILE_NAME, F.FILE_EXT) AS FILE_PATH
FROM USED_GOODS_FILE AS F
WHERE F.BOARD_ID IN (
  SELECT B.BOARD_ID
  FROM USED_GOODS_BOARD AS B
  WHERE B.VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)
)
ORDER BY F.FILE_ID DESC;
